import { Platform } from "react-native";

export const Colors = {
  light: {
    text: "#5A4A42",
    textSecondary: "#A89F9A",
    textDisabled: "#D4CEC9",
    buttonText: "#5A4A42",
    tabIconDefault: "#A89F9A",
    tabIconSelected: "#FFD93D",
    link: "#FFB3C6",
    primary: "#FFD93D",
    primaryTint: "#FFE566",
    secondary: "#FFB3C6",
    accent1: "#A8E6CF",
    accent2: "#A8D8EA",
    success: "#A8E6CF",
    warning: "#FFD93D",
    error: "#FFB3C6",
    backgroundRoot: "#FFF8E7",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#FFF5E0",
    backgroundTertiary: "#FFF0D6",
    surface: "#FFFFFF",
    border: "#F5E6D3",
    vent: "#FFB3C6",
    listen: "#A8E6CF",
  },
  dark: {
    text: "#FFF8E7",
    textSecondary: "#D4CEC9",
    textDisabled: "#8A837E",
    buttonText: "#5A4A42",
    tabIconDefault: "#A89F9A",
    tabIconSelected: "#FFD93D",
    link: "#FFB3C6",
    primary: "#FFD93D",
    primaryTint: "#FFE566",
    secondary: "#FFB3C6",
    accent1: "#A8E6CF",
    accent2: "#A8D8EA",
    success: "#A8E6CF",
    warning: "#FFD93D",
    error: "#FFB3C6",
    backgroundRoot: "#3D3530",
    backgroundDefault: "#4A423C",
    backgroundSecondary: "#524A44",
    backgroundTertiary: "#5A524C",
    surface: "#4A423C",
    border: "#6A625C",
    vent: "#FFB3C6",
    listen: "#A8E6CF",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  "6xl": 64,
  inputHeight: 48,
  buttonHeight: 52,
};

export const BorderRadius = {
  xs: 12,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
  "2xl": 40,
  "3xl": 50,
  full: 9999,
};

export const Typography = {
  h1: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: "700" as const,
    fontFamily: "Nunito_700Bold",
  },
  h2: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "700" as const,
    fontFamily: "Nunito_700Bold",
  },
  h3: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "600" as const,
    fontFamily: "Nunito_600SemiBold",
  },
  h4: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "600" as const,
    fontFamily: "Nunito_600SemiBold",
  },
  body: {
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "400" as const,
    fontFamily: "Nunito_400Regular",
  },
  small: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "400" as const,
    fontFamily: "Nunito_400Regular",
  },
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "400" as const,
    fontFamily: "Nunito_400Regular",
  },
  button: {
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "600" as const,
    fontFamily: "Nunito_600SemiBold",
  },
  link: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "400" as const,
    fontFamily: "Nunito_400Regular",
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "Nunito_400Regular",
    serif: "ui-serif",
    rounded: "Nunito_400Regular",
    mono: "ui-monospace",
  },
  default: {
    sans: "Nunito_400Regular",
    serif: "serif",
    rounded: "Nunito_400Regular",
    mono: "monospace",
  },
  web: {
    sans: "Nunito, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "Nunito, 'SF Pro Rounded', 'Hiragino Maru Gothic ProN', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
